snplist_plink_flag: '--pfile'
snplist_plink_ext: ['.pgen', '.pvar', '.psam']
plink_chr_prefix: 'plink_chr'
plink_chr_suffix: ''

build: '38'

pheno_name: 'BMI'

plink_geno: 0.01
plink_mind: 0.01
plink_maf: 0.01
plink_hwe: 0

sample_plink_flag: 'bfile'
sample_plink_ext: ['.bed', '.bim', '.fam']
sample_plink_prefix: 'plink_sample'

inverse_normal_pheno: 'TRUE'
pheno_covar_colnames: ['PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10, PC11, PC12, PC13, PC14, PC15, AGE, SEX']